version: '3.8'

services:
  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    env_file:
      - ./api/.env.docker
    ports:
      - "${PGPORT}:5432"
      
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001

  mlservice:
    container_name: mlservice
    build:
      context: ./ml-service
      dockerfile: ./Dockerfile
    command: bash -c "python -m app.app"
    ports:
      - "8011:8011"
    volumes:
      - ${PWD}/ml-service/weights:/weights

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: bash -c "./api"
    depends_on:
      - database
      - minio
      - mlservice
    ports:
      - "8001:8001"

volumes:
  minio-storage:
