version: '3.8'

services:
  database:
    container_name: database
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    env_file:
      - .env
    ports:
      - "${PGPORT}:5432"

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "./api"
    depends_on:
      - database
    ports:
      - "8001:8001"
      
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001

volumes:
  minio-storage:
